apiVersion: v1
kind: Pod
metadata:
  name: rqdao-pod-xgl # Replace with your name
spec:
  hostname: xgl
  containers:
  - name: xgl
    image: ghcr.io/selkies-project/nvidia-glx-desktop:latest
    env:
    - name: TZ
      value: "UTC"
    - name: DISPLAY_SIZEW
      value: "1920"
    - name: DISPLAY_SIZEH
      value: "1080"
    - name: DISPLAY_REFRESH
      value: "60"
    - name: DISPLAY_DPI
      value: "96"
    - name: DISPLAY_CDEPTH
      value: "24"
    - name: VIDEO_PORT
      value: "DFP"
    - name: PASSWD
#          value: "mypasswd"
      valueFrom:
        secretKeyRef:
          name: general-pass # Replace with the name of the secret
          key: general-password # Replace with the name of the password (NOT THE ACTUAL PASSWORD)
    - name: SELKIES_ENCODER
      value: "nvh264enc"
    - name: SELKIES_ENABLE_RESIZE
      value: "false"
    - name: SELKIES_VIDEO_BITRATE
      value: "8000"
    - name: SELKIES_FRAMERATE
      value: "60"
    - name: SELKIES_AUDIO_BITRATE
      value: "128000"
    - name: SELKIES_ENABLE_BASIC_AUTH
      value: "true"
    # Defaults to `PASSWD` if unspecified, choose either `value:` or `secretKeyRef:` but not both at the same time
#        - name: SELKIES_BASIC_AUTH_PASSWORD
#          value: "mypasswd"
#          valueFrom:
#            secretKeyRef:
#              name: my-pass
#              key: my-pass
    - name: SELKIES_TURN_REST_URI
      value: "http://turn-rest.nrp-nautilus.io"
    - name: SELKIES_TURN_PROTOCOL
      value: "udp"
    - name: SELKIES_TURN_TLS
      value: "false"
    stdin: true
    tty: true
    ports:
    - name: http
      containerPort: 8080
      protocol: TCP
    resources:
      limits:
        memory: 32Gi
        cpu: "16"
        nvidia.com/gpu: 2
        ephemeral-storage: 512Gi
      requests:
        memory: 32Gi
        cpu: "16"
        nvidia.com/gpu: 2
        ephemeral-storage: 512Gi
    volumeMounts:
    - mountPath: /dev/shm
      name: dshm
    - mountPath: /cache
      name: xgl-cache-vol
    - mountPath: /mnt/persistent
      name: xgl-root-vol
  dnsPolicy: None
  dnsConfig:
    nameservers:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  - name: xgl-cache-vol
    persistentVolumeClaim:
      claimName: rqdao-xgl-cache # Change this to your cache pvc
  - name: xgl-root-vol
    persistentVolumeClaim:
      claimName: rqdao-rook-volume # Change this to your storage pvc
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: NotIn
            values:
            - ucsd-suncave
#              - key: topology.kubernetes.io/region
#                operator: In
#                values:
#                - us-west
